import { $, setRead, clamp, icon, toast } from "../core/ui.js";
import { post } from "../core/api.js";
import { manualBounds } from "../core/range.js";
const WAVE_IDX={sine:0,triangle:1,square:2,saw:3},MOD_IDX={off:0,rate:1,depth:2},MODWAVE_IDX={sine:0,triangle:1,random:2};
export let gen={running:false,wave:"sine",mod:"off"};
function genPayload(){return{wave:WAVE_IDX[gen.wave]??0,rate:parseFloat($("genRate").value),depth:parseInt($("genDepth").value),offset:parseInt($("genOff").value),ease:parseInt($("genEase").value),mod:MOD_IDX[gen.mod]??0,mod_wave:MODWAVE_IDX[$("modWave").value]??0,mod_rate:parseFloat($("modRate").value),mod_amp:parseFloat($("modAmp").value)}}
let gp=null;
export function pushGenParams(){clearTimeout(gp);gp=setTimeout(function(){post("/api/gen",genPayload())},60)}
export function initGenerator(){var ws=$("waveSeg");if(ws)ws.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;ws.querySelectorAll("button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");gen.wave=b.dataset.w;pushGenParams()});var ms=$("modSeg");if(ms)ms.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;ms.querySelectorAll("button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");gen.mod=b.dataset.m;var mc=$("modControls");if(mc)mc.style.display=gen.mod==="off"?"none":"block";pushGenParams()});var sb=$("genStartBtn");if(sb)sb.addEventListener("click",toggleGenerator);["genRate","genDepth","genOff","genEase","modRate","modAmp"].forEach(function(id){var s=$(id);if(!s)return;s.addEventListener("input",function(){setRead(id+"Val",s.value);pushGenParams()})});var mw=$("modWave");if(mw)mw.addEventListener("change",pushGenParams)}
export async function startGenerator(){if(gen.running)return;gen.running=true;await post("/api/gen",Object.assign(genPayload(),{running:true}));var btn=$("genStartBtn");if(btn){btn.innerHTML=icon("i-stop")+" Stop Generator";btn.classList.remove("primary");btn.classList.add("danger")}var note=$("genNote");if(note)note.textContent="Running on the device."}
export async function stopGenerator(){if(!gen.running)return;gen.running=false;await post("/api/gen",{running:false});var btn=$("genStartBtn");if(btn){btn.innerHTML=icon("i-play")+" Start Generator";btn.classList.add("primary");btn.classList.remove("danger")}var note=$("genNote");if(note)note.textContent="Generated on the device — keeps running even if you close this tab."}
export function toggleGenerator(){gen.running?stopGenerator():startGenerator()}
