import { $, setRead, clamp, icon, toast } from "../core/ui.js";
import { post } from "../core/api.js";
import { manualBounds } from "../core/range.js";
const WAVE_IDX={sine:0,triangle:1,square:2,saw:3},MOD_IDX={off:0,rate:1,depth:2},MODWAVE_IDX={sine:0,triangle:1,random:2};
export let gen={running:false,wave:"sine",mod:"off"};
function genPayload(){return{wave:WAVE_IDX[gen.wave]??0,rate:parseFloat($("genRate").value),depth:parseInt($("genDepth").value),offset:parseInt($("genOff").value),ease:parseInt($("genEase").value),mod:MOD_IDX[gen.mod]??0,mod_wave:MODWAVE_IDX[$("modWave").value]??0,mod_rate:parseFloat($("modRate").value),mod_amp:parseFloat($("modAmp").value)}}
let gp=null;
export function pushGenParams(){clearTimeout(gp);gp=setTimeout(function(){post("/api/gen",genPayload())},60)}
export function initGenerator(){var ws=$("waveSeg");if(ws)ws.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;ws.querySelectorAll("button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");gen.wave=b.dataset.w;pushGenParams()});var ms=$("modSeg");if(ms)ms.addEventListener("click",function(e){var b=e.target.closest("button");if(!b)return;ms.querySelectorAll("button").forEach(function(x){x.classList.remove("active")});b.classList.add("active");gen.mod=b.dataset.m;var mc=$("modControls");if(mc)mc.style.display=gen.mod==="off"?"none":"block";pushGenParams()});var sb=$("genStartBtn");if(sb)sb.addEventListener("click",toggleGenerator);["genRate","genDepth","genOff","genEase","modRate","modAmp"].forEach(function(id){var s=$(id);if(!s)return;s.addEventListener("input",function(){setRead(id+"Val",s.value);pushGenParams()})});var mw=$("modWave");if(mw)mw.addEventListener("change",pushGenParams);var vt=$("waveVizTog");if(vt)vt.addEventListener("change",toggleWaveViz)}
export async function startGenerator(){if(gen.running)return;gen.running=true;await post("/api/gen",Object.assign(genPayload(),{running:true}));var btn=$("genStartBtn");if(btn){btn.innerHTML=icon("i-stop")+" Stop Generator";btn.classList.remove("primary");btn.classList.add("danger")}var note=$("genNote");if(note)note.textContent="Running on the device."}
export async function stopGenerator(){if(!gen.running)return;gen.running=false;await post("/api/gen",{running:false});var btn=$("genStartBtn");if(btn){btn.innerHTML=icon("i-play")+" Start Generator";btn.classList.add("primary");btn.classList.remove("danger")}var note=$("genNote");if(note)note.textContent="Generated on the device."}
export function toggleGenerator(){gen.running?stopGenerator():startGenerator()}
function carrier(wave,p){switch(wave){case"triangle":return p<0.5?p*2:2-2*p;case"square":return p<0.5?1:0;case"saw":return p;default:return 0.5-0.5*Math.cos(p*2*Math.PI)}}
function easeV(v){var e=parseFloat($("genEase").value)/100;if(e<=0)return v;var s=v*v*(3-2*v);return v+(s-v)*e}
var wvOn=true,wvRAF=null;
export function toggleWaveViz(){wvOn=$("waveVizTog").checked;var wrap=$("waveCanvasWrap");if(wrap)wrap.style.display=wvOn?"block":"none";if(wvOn&&!wvRAF)wvRAF=requestAnimationFrame(drawWaveViz)}
function drawWaveViz(){wvRAF=wvOn?requestAnimationFrame(drawWaveViz):null;var cv=$("waveCanvas");if(!cv||!wvOn)return;var dpr=window.devicePixelRatio||1,w=cv.clientWidth,h=cv.clientHeight;if(cv.width!==w*dpr||cv.height!==h*dpr){cv.width=w*dpr;cv.height=h*dpr}var ctx=cv.getContext("2d");ctx.setTransform(dpr,0,0,dpr,0,0);ctx.clearRect(0,0,w,h);var off=parseFloat($("genOff").value)/100,bd=parseFloat($("genDepth").value)/100,center=off;var t=performance.now()/1000,rate=parseFloat($("genRate").value);ctx.strokeStyle="rgba(154,160,196,.25)";ctx.lineWidth=1;ctx.beginPath();ctx.moveTo(0,2);ctx.lineTo(w,2);ctx.moveTo(0,h-2);ctx.lineTo(w,h-2);ctx.stroke();ctx.beginPath();for(var x=0;x<=w;x++){var ph=((x/w)*2*rate+t*rate)%1,depth=bd;if(gen.mod!=="off"){var mph=(t*parseFloat($("modRate").value))%1,mwv=$("modWave").value;var m=mwv==="triangle"?(mph<0.5?mph*2:2-2*mph):(mwv==="random"?0.5:(0.5-0.5*Math.cos(mph*2*Math.PI)));if(gen.mod==="depth"){var amt=clamp(parseFloat($("modAmp").value)/Math.max(rate,0.1),0,1);depth=clamp(depth*(1-0.5*m*amt),0.02,1)}}var c=easeV(carrier(gen.wave,ph)),frac=clamp(center+(c-0.5)*depth,0,1),y=h-(frac*(h-6)+3);x===0?ctx.moveTo(x,y):ctx.lineTo(x,y)}ctx.strokeStyle=gen.running?"#34d399":"#6c8cff";ctx.lineWidth=2;ctx.stroke()}
