#!/usr/bin/env python3
"""segtrace_to_case -- turn a segtrace pull into a slopmotion regression case.

Reads a `segtrace-<run>` directory as written by tools/segtrace.py (segin.txt
for what the client sent, plan.txt for what the engine did with it) and emits
the C++ literal the native suite replays: a `fieldreplay::S[]` table plus the
`Config` initializer that names the tuning it ran under. A field figure becomes
a regression case in one step, never by hand (T20: a hand-copied vocabulary
drifts silently).

`--state` takes a JSON dump of the machine's slopmotion STATE fields (channels
0x1122 / 0x1121 / 0x1120), keys named exactly as the device catalog names them
(curve_policy, infeasible_policy, smooth_budget, amp_budget, blend_steps,
infeas_blend, settle_grace_ms, chase_gain, chase_look, ...). Without it the
Config falls back to the suite's own liveTuning() values, which are the same
machine read on 2026-09-02.

Usage:
  python tools/segtrace_to_case.py --dir artifacts/segtrace-jitter-06 \\
      --from 158.4 --to 166.2 --name hold_figure
  python tools/segtrace_to_case.py --dir artifacts/segtrace-jitter-07 \\
      --state artifacts/sm-state.json --out
"""
import argparse, json, os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# The device's own live tuning, 2026-09-02, window 87-187 mm. Same numbers as
# fieldreplay::liveTuning() in test/native/test_slopmotion/test_main.cpp; a
# --state dump overrides every field it names.
DEFAULT_STATE = {
    'window_mm': 100.0,
    'input_max_speed': 1000.0,     # mm/s
    'input_max_accel': 40000.0,    # mm/s^2
    'input_max_jerk': 5000000.0,   # mm/s^3
    'user_max_speed': 200.0,       # mm/s -> recovery_vmax
    'infeasible_policy': 1,        # Blend
    'infeas_blend': 0.5,
    'smooth_budget': 0.5,
    'amp_budget': 0.5,
    'blend_steps': 6,
    'settle_grace_ms': 200,
    'chase_gain': 0.1,
    'chase_look': 0.0,
    'curve_policy': 0,
}

# `vf=S0.000` / `next=-0.000`: the S3's plan/segin lines prefix a SENTINEL
# (field absent on the wire) rather than omitting the key (src/main.cpp:1029).
LINE = re.compile(r'\[\s*([\d.]+) [IW] (segin|plan)\] (.*)')
NUM = re.compile(r'(\w+)=(\S+)')
KIND = re.compile(r'-> (\w+)/(\w+)')


def parse(path, tag):
    rows = []
    if not os.path.exists(path):
        return rows
    for line in open(path, encoding='utf-8', errors='replace'):
        m = LINE.match(line)
        if not m or m.group(2) != tag:
            continue
        d = dict(NUM.findall(m.group(3)))
        if 'due' not in d:
            continue
        d['t'] = float(m.group(1))
        d['_refused'] = 'REFUSED' in line
        k = KIND.search(line)
        d['_kind'] = k.group(1) if k else None
        rows.append(d)
    return rows


def sentinel(text, mark):
    """('S0.000', 'S') -> (0.0, False);  ('2.817', 'S') -> (2.817, True)."""
    if text.startswith(mark):
        return 0.0, False
    return float(text), True


def rows_for(directory, t_from, t_to):
    segin = parse(os.path.join(directory, 'segin.txt'), 'segin')
    plan = {p['due']: p for p in parse(os.path.join(directory, 'plan.txt'), 'plan')}
    out = []
    for s in segin:
        if not (t_from <= s['t'] <= t_to):
            continue
        p = plan.get(s['due'])
        vf, has_vf = sentinel(s['vf'], 'S')
        nxt, has_next = sentinel(p['next'], '-') if p else (0.0, False)
        # late= is the queue-drain lag the S3 measured for THIS commit, which is
        # the row's own late_ms. No plan line means the commit never happened.
        late_ms = round(int(p['late']) / 1000.0) if p else 0
        out.append({
            'due': int(s['due']), 't': s['t'],
            'tgt': float(s['tgt']), 'dur_ms': int(s['dur']),
            'vf': vf, 'has_vf': has_vf, 'next': nxt, 'has_next': has_next,
            'late_ms': late_ms, 'fam': int(s.get('fam', 1)),
            'kind': p['_kind'] if p else None,
            'refused': bool(p and p['_refused']),
        })
    return out


def emit(rows, state, name):
    span = state['window_mm']
    lines = []
    lines.append('// Generated by tools/segtrace_to_case.py -- do not hand-edit.')
    lines.append('Config %sTuning() {' % name)
    lines.append('    Config cfg;')
    lines.append('    cfg.limits.vmax = %.1ff;      // %g mm/s / %g mm'
                 % (state['input_max_speed'] / span, state['input_max_speed'], span))
    lines.append('    cfg.limits.amax = %.1ff;     // %g mm/s2 / %g mm'
                 % (state['input_max_accel'] / span, state['input_max_accel'], span))
    lines.append('    cfg.limits.jmax = %.1ff;  // %g mm/s3 / %g mm'
                 % (state['input_max_jerk'] / span, state['input_max_jerk'], span))
    lines.append('    cfg.recovery_vmax   = %.1ff;'
                 % (state['user_max_speed'] / span))
    # 0 = Stretch, 1 = Blend; ordinals 2..5 are the policies deleted 2026-09-02
    # and an older NVS may still hold one. The host map runs those as Blend, so
    # this does too (include/system/SystemState.h, sm_tune_infeas_policy).
    lines.append('    cfg.infeasible_policy = InfeasiblePolicy::%s;'
                 % ('Stretch' if int(state['infeasible_policy']) == 0 else 'Blend'))
    # 0 = FollowClient, which is the machine's default and the engine's, so it is
    # left unwritten; the per-row client family carries c1_cubic instead.
    fam = int(state.get('curve_policy', 0))
    if fam:
        lines.append('    cfg.curve_policy = slopmotion::CurvePolicy::Force%s;'
                     % ('C1' if fam == 1 else 'C2'))
    lines.append('    cfg.infeasible_blend            = %.3ff;' % state['infeas_blend'])
    lines.append('    cfg.infeasible_smooth_budget    = %.3ff;' % state['smooth_budget'])
    lines.append('    cfg.infeasible_amplitude_budget = %.3ff;' % state['amp_budget'])
    lines.append('    cfg.infeasible_blend_steps      = %d;' % int(state['blend_steps']))
    lines.append('    cfg.settle_grace_us = %d;' % int(state['settle_grace_ms'] * 1000))
    lines.append('    cfg.chase_ff_gain   = %.3ff;' % state['chase_gain'])
    lines.append('    cfg.chase_lookahead = %.1ff;' % state['chase_look'])
    lines.append('    return cfg;')
    lines.append('}')
    lines.append('')
    if rows:
        lines.append('// %.3f-%.3f s, %d segments, client curve family %d.'
                     % (rows[0]['t'], rows[-1]['t'], len(rows), rows[0]['fam']))
    lines.append('const S %s[] = {' % name)
    for r in rows:
        lines.append('    {%.3ff, %4d, %7.3ff, %5s, %6.3ff, %5s, %2d},'
                     % (r['tgt'], r['dur_ms'], r['vf'], str(r['has_vf']).lower(),
                        r['next'], str(r['has_next']).lower(), r['late_ms']))
    lines.append('};')
    return '\n'.join(lines) + '\n'


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--dir', required=True, help='segtrace-<run> directory to read')
    ap.add_argument('--state', default=None,
                    help='JSON of the 0x1122/0x1121/0x1120 STATE fields')
    ap.add_argument('--from', dest='t_from', type=float, default=0.0,
                    help='first segin timestamp to keep, seconds')
    ap.add_argument('--to', dest='t_to', type=float, default=1e12,
                    help='last segin timestamp to keep, seconds')
    ap.add_argument('--name', default='F', help='C++ identifier for the table')
    ap.add_argument('--out', nargs='?', const='', default=None,
                    help='write beside artifacts/ instead of stdout')
    a = ap.parse_args()

    state = dict(DEFAULT_STATE)
    if a.state:
        state.update(json.load(open(a.state, encoding='utf-8')))
    rows = rows_for(a.dir, a.t_from, a.t_to)
    if not rows:
        print('no segin rows in %s over [%g, %g]' % (a.dir, a.t_from, a.t_to),
              file=sys.stderr)
        return 1
    text = emit(rows, state, a.name)
    if a.out is None:
        sys.stdout.write(text)
    else:
        path = a.out or os.path.join(
            ROOT, 'artifacts', os.path.basename(os.path.normpath(a.dir))
            + '-' + a.name + '.inc')
        os.makedirs(os.path.dirname(path), exist_ok=True)
        open(path, 'w', encoding='utf-8').write(text)
        print('%d rows -> %s' % (len(rows), path), file=sys.stderr)
    refused = sum(1 for r in rows if r['refused'])
    missing = sum(1 for r in rows if r['kind'] is None)
    if refused or missing:
        print('note: %d refused, %d segments with no plan line'
              % (refused, missing), file=sys.stderr)
    return 0


if __name__ == '__main__':
    sys.exit(main())
